/*
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BoldAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("nl/mikero/andle/parser/antlr/internal/InternalBold.tokens");
	}
}
