/*
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle.parser.antlr;

import com.google.inject.Inject;
import nl.mikero.andle.parser.antlr.internal.InternalBoldParser;
import nl.mikero.andle.services.BoldGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BoldParser extends AbstractAntlrParser {

	@Inject
	private BoldGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBoldParser createParser(XtextTokenStream stream) {
		return new InternalBoldParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Text";
	}

	public BoldGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BoldGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
