/*
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCodeScopeProvider extends DelegatingScopeProvider {
}
