/*
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BoldRuntimeModule extends AbstractBoldRuntimeModule {
}
