/*
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BoldStandaloneSetup extends BoldStandaloneSetupGenerated {

	def static void doSetup() {
		new BoldStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
