/**
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle;

import nl.mikero.andle.AbstractCodeRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class CodeRuntimeModule extends AbstractCodeRuntimeModule {
}
