/**
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle;

import nl.mikero.andle.CodeStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class CodeStandaloneSetup extends CodeStandaloneSetupGenerated {
  public static void doSetup() {
    new CodeStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
