/**
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle;

import nl.mikero.andle.BoldStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BoldStandaloneSetup extends BoldStandaloneSetupGenerated {
  public static void doSetup() {
    new BoldStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
