/*
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle.ui.tests;

import com.google.inject.Injector;
import nl.mikero.andle.bold.lang.ui.internal.LangActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class BoldUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LangActivator.getInstance().getInjector("nl.mikero.andle.Bold");
	}

}
