/*
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CodeStandaloneSetup extends CodeStandaloneSetupGenerated {

	def static void doSetup() {
		new CodeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
