/**
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle.validation;

import nl.mikero.andle.validation.AbstractCodeValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CodeValidator extends AbstractCodeValidator {
}
