/**
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle.ide;

import nl.mikero.andle.ide.AbstractCodeIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class CodeIdeModule extends AbstractCodeIdeModule {
}
