/*
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle.ide

import com.google.inject.Guice
import nl.mikero.andle.BoldRuntimeModule
import nl.mikero.andle.BoldStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BoldIdeSetup extends BoldStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BoldRuntimeModule, new BoldIdeModule))
	}
	
}
