/**
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle.ui.contentassist;

import nl.mikero.andle.ui.contentassist.AbstractCodeProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CodeProposalProvider extends AbstractCodeProposalProvider {
}
