/**
 * generated by Xtext 2.13.0
 */
package nl.mikero.andle.scoping;

import nl.mikero.andle.scoping.AbstractCodeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CodeScopeProvider extends AbstractCodeScopeProvider {
}
